### ISSUE TITLE
Implement custom options

### ISSUE THREAD

**Issue by Madnex** [mmozeiko/RcloneBrowser#11]
First of all: Great app! Works like a charme :)

I have two suggestions:

1. It would be very cool to add custom options when configuring an upload. e.g I need to add the "--acd-upload-wait-per-gb" option and instead of implementing this with another checkbox this could be a more flexible way? So maybe a feature to add these custom options to a list? 

2. Is it possible to (server-side) move/copy folders with RcloneBrowser on the remote itself?

**Comment by mmozeiko** [comment]
1. Good suggestion. I'll implement it as additional text field where you can put any rclone option you want.

2. It's possible like this - you need to go to source file or folder and press "Download" for it. Then in destination simply type remote-name:/destination/folder. Destination must be a folder. If source is a file, then it will will be placed in destination folder with same file name (I am not yet using new rclone copyto and moveto commands). Destination folder will be created if it doesn't exist. Not a very nice way, but it works. I couldn't figure out nice way to allow this in GUI.

**Comment by Madnex** [comment]
1. Great work! 
2. Didn't know about this. Good to know 👍
