### ISSUE TITLE
Determining which folder is most recently modified is excessively hard, especially in the UK

### ISSUE THREAD

**Issue by CottonEaster** [mmozeiko/RcloneBrowser#113]
In the situation pictured by the screenshot below, I wished to determine which subfolder of 'scripts' was the most recently modified. Doing so was hard, especially since rclone-browser's date format is not following my - United Kingdom - locale.

![image](https://user-images.githubusercontent.com/9998846/39792795-5cade2e6-533a-11e8-8dbb-8168ea48cb22.png)

**Comment by mmozeiko** [comment]
Isn't that obvious that Sat is recently modified, because it is at the top (because you are sorting on Modified column)?

**Comment by CottonEaster** [comment]
On reflection, yes. But I wish that (1) it were more obvious which field is determining the order, and I wish that (2) RcloneBrowser were to use my local date formatting.

Still, 1 - and even 2? - may owe to theme or to the qt toolkit rather than to RcloneBrowser.
