### ISSUE TITLE
encrypted config not imported

### ISSUE THREAD

**Issue by 2600box** [mmozeiko/RcloneBrowser#12]
I have rclonebrowser 1.1 on a mac

rclonebrowser opens a terminal window and asks for password. i enter the password and i have the following output in the terminal window, and nothing in the application, so no remotes are added.

conf file is in home directory. rclone is in `/Users/quietmouse/.go/bin/rclone`

`/tmp/rclone_config.command ; exit;`
```
Enter configuration password:
password:
Usage:
  rclone [flags]
  rclone [command]
SNIP! SNIP! SNIP!
Use "rclone [command] --help" for more information about a command.
Command not found.
/tmp/rclone_config.command: line 3: config: command not found
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.
```

`cat /tmp/rclone_config.command` gives
```
#!/bin/sh
/Users/quietmouse/.go/bin/rclone
 config
```

**Comment by pizzadude** [comment]
Same in Linux Mint 18 (Ubuntu 16.04)

**Comment by mmozeiko** [comment]
@2600box hmm, I tried it and it seems to work fine for me.

1) Does any other rclone command work? Like do the list of remotes show up correctl? What about browsing remote folders?

2) Can you please gui config to see if it has correct location for rclone. To do so, execute this in terminal:

    `plutil -convert xml1 -o - ~/Library/Preferences/com.rclonecommander.RcloneCommander.plist`

    It should have <string>/Users/quietmouse/.go/bin/rclone</string> without any newlines.

3) what if you don't have password protected .rclone.config file? Does "config" button then works correctly?

@pizzadude what terminal are you using by default?

**Comment by 2600box** [comment]
Remotes do not show up correctly and I cannot do anything but look at preferences and the empty 'Remotes/Jobs' window.

It may be more complicated, but it looks like it is throwing an extra carriage return between `/Users/quietmouse/.go/bin/rclone` and `config` in the `/tmp/rclone_config.command`


`plutil -convert xml1 -o - ~/Library/Preferences/com.rclonecommander.RcloneCommander.plist` returns the following:
`/Users/quietmouse/Library/Preferences/com.rclonecommander.RcloneCommander.plist: file does not exist or is not readable or is not a regular file (Error Domain=NSCocoaErrorDomain Code=260 "The file “com.rclonecommander.RcloneCommander.plist” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/Users/quietmouse/Library/Preferences/com.rclonecommander.RcloneCommander.plist, NSUnderlyingError=0x7fc545502900 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}})`

however `com.rclone-browser.rclone-browser.plist` exists and has the following:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>MainWindow.geometry</key>
	<data>
	hash1=
	</data>
	<key>Settings.alwaysShowInTray</key>
	<true/>
	<key>Settings.closeToTray</key>
	<false/>
	<key>Settings.mount</key>
	<string></string>
	<key>Settings.notifyFinishedTransfers</key>
	<true/>
	<key>Settings.rclone</key>
	<string>/Users/quietmouse/.go/bin/rclone
</string>
	<key>Settings.rowColors</key>
	<false/>
	<key>Settings.showFileIcons</key>
	<true/>
	<key>Settings.showFolderIcons</key>
	<true/>
	<key>Settings.stream</key>
	<string></string>
</dict>
</plist>
```

**Comment by mmozeiko** [comment]
It looks that somehow \n symbol is at of setting for path to rclone. Try editing plist file and remove the \n symbol. So line after `<key>Settings.rclone</key>` should look like this: `<string>/Users/quietmouse/.go/bin/rclone</string>`.

Not sure how that happened. I'll add code to remove any whitespace at end (and at beginning) of rclone setting.

**Comment by 2600box** [comment]
got it. i must have copied it from the terminal. works as expected now.
