### ISSUE TITLE
Show rclone command 

### ISSUE THREAD

**Issue by UBy** [mmozeiko/RcloneBrowser#131]
It would be nice if the output box in the Jobs tab would show what rclone command is being run.

I started using the rclone browser, because I didn't want learn all the cmd line arguments, but I would still like to see them in case I want to use a command from a cron job.

**Comment by HerrSoost** [comment]
There is a button in the jobs tab to copy the command to the clipboard:
(Ubuntu 16.04)
![screen](https://user-images.githubusercontent.com/32292852/46099722-d02c0a80-c1c7-11e8-8a63-bdacca06cb67.png)
