### ISSUE TITLE
Export list of files in folder

### ISSUE THREAD

**Issue by mmozeiko** [mmozeiko/RcloneBrowser#17]
Allow user to export list of files to text file.
Offer to export only file names, or full CSV format that includes date and size.

**Comment by kajeagentspi** [comment]
use the data to count how many files there are remaining to be downloaded

**Comment by mmozeiko** [comment]
Counting files won't solve "remaining time / progress bar" problem. rclone adds new files while its downloading existing ones, or some transfers occasionally fail so it retries them. There's no reasonable way to know how many files are remaining for a transfer.
