### ISSUE TITLE
Dropbox with RcloneBrowser 

### ISSUE THREAD

**Issue by luizaugustopc** [mmozeiko/RcloneBrowser#18]
RcloneBrowser only displays folder and files into Dropbox remote folder.
Dropbox:Folder (display)
Dropbox:File (display)
Dropbox:Folder/Folder (no display)
Dropbox:Folder/File (no display)
Lists files hierarchically is displayed correctly by rclone only.
Running both rclone and rclone-browser updated under Ubuntu 16.10 updated too.
TIA

**Comment by mmozeiko** [comment]
This is a bug. And I can reproduce it. For me it shows some files and folders under top folder, but some not. It's really strange. I'll look into this.

**Comment by mmozeiko** [comment]
It seems that something is wrong with rclone itself. I get exactly same behaviour also with rclone command line tool. See this issue in rclone repo: ncw/rclone#1103

**Comment by luizaugustopc** [comment]
Yes, Rclone works correctly. The problem only happens on Rclone Browser. It's strange.

**Comment by mmozeiko** [comment]
Can you try execute `rclone lsl --max-depth 1 DropboxRemote:Folder` ? Folder should be one who doesn't show anything inside in GUI.

**Comment by luizaugustopc** [comment]
~$ rclone lsl --max-depth 1 Dropbox:Photos
2017/02/07 18:50:08 path "/Photos/How to use the Photos folder.rtf" is not under root "/Photos/"

Look GUI image after loding Public Folder bellow.
![captura de tela de 2017-02-07 18-55-59](https://cloud.githubusercontent.com/assets/7927584/22711197/776f2b38-ed67-11e6-8c5b-fd89d6e7d0e6.png)

**Comment by mmozeiko** [comment]
Yes, this is exactly the what I wrote in issue #1103 - it's a bug in rclone. It thinks there are no files in folder, but there are.

**Comment by luizaugustopc** [comment]
Take a look that:
~$ rclone ls Dropbox:Public
     1072 How to use the Public folder.rtf
   288428 446.0001(1).pdf

It list files perfectly under "ls" command.

**Comment by mmozeiko** [comment]
That's exactly what I wrote in 1103. Have you actually read it? ls works, but together with `--max-depth 1` it doesn't. My GUI needs to use --max-depth, otherwise rclone will start fetching full tree recursively, and that may take a very long time for large remotes.

**Comment by mmozeiko** [comment]
rclone beta v1.35 fixes this bug: https://github.com/ncw/rclone/issues/1103#issuecomment-282468824
