### ISSUE TITLE
Support custom .rclone.conf file location

### ISSUE THREAD

**Issue by mmozeiko** [mmozeiko/RcloneBrowser#21]

**Comment by CottonEaster** [comment]
I too am having trouble with RcloneBrowser (version 1.2) seeing my `rclone.conf` on Windows (Windows 8.1 x64). I've tried putting the conf file in `C:\Users\<username>\.config\rclone` and in `C:\Users\<username>` but neither seems to work. I've to Rclone 1.38 (and, if this is relevant, the `rclone.conf` is copied from a working Linux installation of Rclone).

**Comment by mmozeiko** [comment]
Do you want custom location or default one?
For default one just execute `rclone config file`. It will show location where rclone expects config file to be. It supports multiple locations by defaault, but this command will show just the first default location.

**Comment by CottonEaster** [comment]
Thanks, but `rclone config file' shows

`C:\Users\<username>\.config\rclone\rclone.conf`

which is where my conf file is _already_ and yet . . no dice.

**Comment by mmozeiko** [comment]
Have you set custom rclone.conf location in File->Preferences? Remove it, if you have.

**Comment by CottonEaster** [comment]
I had set that. I've removed it. No change. By the way, I wasn't sure whether that dialogue wanted the full path, including the leafname, or just the folder. I still have a custom location set for rclone itself.

**Comment by mmozeiko** [comment]
That field needs full path to .conf file itself, not just the folder. If the field is empty (make sure its empty and not set to space or smth) then RcloneBrowser will use exactly same path has "rclone config file" command shows.

You can check registry setting `rconeConf` in `Computer\HKEY_CURRENT_USER\Software\rclone-browser\rclone-browser\Settings`. If it is set to anything, just delete it.

**Comment by CottonEaster** [comment]
The registry key was blank. I deleted it entirely. No change. I provided full paths (including leafnames) to the Preferences window, for rclone.conf and for rclone.conf. No change. I clicked the 'config' button. Nothing happened.

I am on the verge of giving up.
