### ISSUE TITLE
Not sure how to launch terminal

### ISSUE THREAD

**Issue by ardika** [mmozeiko/RcloneBrowser#24]
Hi, i can't open config menu, it's said:

> Not sure how to launch terminal!
Please set path to terminal executable in $TERMINAL environment variable.

however i already set env variable TERMINAL with my xfce4-terminal but problem exists. Thanks.

![deepinscreenshot20170210213315](https://cloud.githubusercontent.com/assets/4718951/22830475/3b58fe20-efd9-11e6-971d-ba1a963c8f4e.png)
![deepinscreenshot20170210213258](https://cloud.githubusercontent.com/assets/4718951/22830476/3b5dd60c-efd9-11e6-95ba-91f428e9401a.png)

**Comment by mmozeiko** [comment]
When you set environment variable, did you launch GUI from same terminal, or new one? Because environment variable is set only for current "window". And if you set it permanently somewhere in .profile or .bashrc, then you need to restart GUI for it to reload env variables.

**Comment by ardika** [comment]
@mmozeiko thanks for the answer. so i just realize that's how env variable works:

> Because environment variable is set only for current "window"

i'm glad you pointing it out for me, im starting it from different terminal actually so the problems exist. however i already add export command in profile.d too but after restarting rclone-browser problem still occurred, maybe should i logout first?. But by info from about how env variable works then i have idea to edited rclone-browser menu from menulibre and change it command launcher to:

`bash -c "export TERMINAL=/usr/bin/xfce4-terminal && /usr/bin/rclone-browser"`

then problem solved. thanks for your help and btw this is an awesome project!.

**Comment by mmozeiko** [comment]
You should be able to put "export TERMINAL=..." inside ~/.bashrc. And then it should work when launching GUI from new terminal or application launcher.

**Comment by ardika** [comment]
@mmozeiko thats a better idea... thanks :+1:
