### ISSUE TITLE
Check how to build Ubuntu .deb files

### ISSUE THREAD

**Issue by mmozeiko** [mmozeiko/RcloneBrowser#26]
Maybe provide releases also as .deb files for easier installation on Ubuntu.

**Comment by Stele77** [comment]
This would be GREAT! i am a noob to Linux, and never compiled myself, will try to work myself into making a .deb file, but a precompiled one would of course be greatly welcomed!
Anyway, thanks for this awesome piece of software!
Greetings
Steven

**Comment by mmozeiko** [comment]
This is almost done on the creating-deb brach. I just need to put everything together and create 1.2 release which will have deb files.

**Comment by hotice** [comment]
I uploaded RcloneBrowser to my PPA, see here: http://www.webupd8.org/2017/01/rclonebrowser-rclone-gui-lets-you.html

**Comment by mmozeiko** [comment]
Thanks for doing this. I think I'll be doing this myself starting with next release. It took me a while to get it right, I haven't been building .deb packages before. But now it's pretty much done. Creating Arch packages it is so much simpler :)
