### ISSUE TITLE
RcloneBrowser Portable

### ISSUE THREAD

**Issue by Kodiman** [mmozeiko/RcloneBrowser#28]
Hi, Your RcloneBrowser is excellent! Please add an option or version for it to be a portable app. This allows it to be moved and run from portable drives such as USB flash drives. In other words, store the app settings and configuration in the RcloneBrowser.exe folder. Also, keep rclone.exe and rclone.conf in that folder or subfolders. And, have your app support the rclone.exe --config parameter to tell rclone to look in that folder. Please make it as portable as possible. Thanks.

**Comment by mmozeiko** [comment]
I actually wanted to make portable option, but I totally forgot about it. I'll implement this for 1.2
As for custom rclone.config location, this is currently implemented, but not released yet: #21 I'll make sure this works also for relative paths which is how it will be used in portable mode.

**Comment by Kodiman** [comment]
hi. excellent. superb. you are the best. thanks.
