### ISSUE TITLE
unable to ru RClone Browser on Win64

### ISSUE THREAD

**Issue by stefano70** [mmozeiko/RcloneBrowser#29]
Hello,
I am a RClone fanatic and I use it on both Linux and Windows with ACD.

Unfortunately I am not able to use RCloneBrowser on Windows.
I run it, I provide the path to Rclone.exe, but then I can not see any remote even if it perfectly locate the config file.
Any idea or suggestions?

**Comment by mmozeiko** [comment]
Do you have .rclone.conf in custom location? Current release supports only default .rclone.conf location - in %USERPROFILE% folder. I have implemented custom location in #21, but it is not released yet.

**Comment by stefano70** [comment]
Exactly!
USERPROFILE=c:\users\stefano
and the config file ".rclone.conf" is there
USERPROFILE=c:\users\stefano\.rclone.config

Running RCloneBrowser and clicking on the "Config..." button this action open the command prompt and launch the rclone config command.

**Comment by mmozeiko** [comment]
Few questions to understand the problem:
1) do you have password protected .rclone.conf file?
2) when you click config button and rclone opens in new command prompt, does it show remotes there?
3) if you open cmd.exe and execute this `rclone listremotes -l` , what output do you see? You can obfuscate remote names, I don't need exact names, just the formatting.

**Comment by stefano70** [comment]
Many thanks for your help... in the meanwhile, I solved!
I upgraded Rclone from 1.33 to 1.35 and now RCloneBrowser works! :-)

anyway, 1) no password protected conf file, 2) yes it shows the remotes, 3) yes it shows my remotes.

Maybe I missed the requirements to use Rclone 1.35 and not the old 1.33

**Comment by mmozeiko** [comment]
Ok. I've never tested it with 1.33. I started to use 1.34 with my GUI. It might be 1.33 lists remotes in a bit different format, that's why GUI doesn't see them. I'll check it.

**Comment by mmozeiko** [comment]
Yeah, I checked 1.33 version, and my tool won't work with it. 1.33 version doesn't have ability to list remotes.
