### ISSUE TITLE
possible to stream with vlc? 

### ISSUE THREAD

**Issue by Dedsec1** [mmozeiko/RcloneBrowser#3]
Hey,

first off, good job on this tool!, plus i love the fact its cross platform which makes it even better for people to use. so whenever i  try to use   ‪C:\Program Files\VideoLAN\VLC\vlc.exe in the stream command. i see the tool saying streaming for about five seconds then finishes.  but overall great tool and keep up the great work with this 👍

**Comment by mmozeiko** [comment]
Yes, it is possible. I have tried couple videos I have in VLC and it works fine.
For VLC you need to enter following command as stream command in preferences:

    "C:\Program Files\VideoLAN\VLC\vlc.exe" -

Quotes are important, because path contains space. And `-` at the end means to read data from stdin which rclone will be providing.

**Comment by Dedsec1** [comment]
so i just tested it from cli and it works just fine, but when i right click and hit stream, vlc opens but wont stream the file right away in vlc.

**Comment by mmozeiko** [comment]
When you say "wont stream the file right away in vlc" - do you mean it starts after some time? Or it doesn't start at all? Or your initial statement - that GUI says stream finished after ~5 seconds and nothing shows up in VLC?

**Comment by amaklp** [comment]
It works but I can't skip to a certain time. Only pause and play.

**Comment by mmozeiko** [comment]
This is expected behavior. That's how rclone works - it simply reads file byte by byte from cloud and passes this information to player. If player wants to seek, it has no way to tell this to rclone. So you can watch videos from beginning to end without seeking, only pausing.

If you want to have seeking support, you need to mount the remoet folder. This is currently possible only on macOS, GNU/Linux and FreeBSD.

**Comment by amaklp** [comment]
Thanks for the answer! I though so because it works when I mount it on a Linux platform.
I guess it's not in the plans to implement the mount function on Windows right? (Yeah, I know it's an extremely complicated issue :P )

Anyways you've done a very good GUI, it's very useful thank you :)

**Comment by mmozeiko** [comment]
There is nothing extra planned to implement in GUI, except make mount button visible which would call rclone.exe to do actual mounting. But there are things happening in rclone itself to support mounting, read here: andrewiankidd/rcloneExplorer#21

**Comment by duczz** [comment]
is it normal that i can not fast-forward a video?

**Comment by mmozeiko** [comment]
Yes, this is expected. rclone reads data sequentially from remote and passes it to media player. Player application has no way to communicate anything back to rclone to seek forward or backwards, so all it can do is just play media file sequentially (or pause).

**Comment by AndyIbanez** [comment]
What is the right way to do this on Mac?

I wrote the vlc's executable path (which I got with the `which` command), but it only opens VLC without the URL to stream.

`/usr/local/bin/vlc`

**Comment by mmozeiko** [comment]
@AndyIbanez did you add `-` at the end? `-` sign as argument to vlc informs to read media data from stdin, which is where rclone will pass the data.

**Comment by sscotth** [comment]
I installed VLC on macOS via Homebrew Cask and am using this stream command to get VLC to work:

`/Applications/VLC.app/Contents/MacOS/VLC -`

**Comment by caspertone2003** [comment]
I was experiencing VLC not working stating: 

"Your input can't be opened
VLC is unable to open the MRL 'fd://0'. Check the log for details."

working ok in two machines, no go on the other. Same versions of OS, rclone, rclonebrowser, vlc....

"the" solution was installing java in the machine where it was not working.

The idea came reading https://github.com/caprica/vlcj/issues/601

So, looks that RCloneBrowser or VLC NEEDS java installed for streaming to work... if it is RcloneBrowser, perhaps should be indicated in the readme....

Thanks!

**Comment by mmozeiko** [comment]
Sounds like issue with OSX and SIP, not java installation. rclone or RcloneBrowser DOES NOT need java. And afaik VLC also DOES NOT need java.
