### ISSUE TITLE
After cycling directory name (a>b>a), Rclone Browser doesn't refresh the directory properly.

### ISSUE THREAD

**Issue by the-researcher** [mmozeiko/RcloneBrowser#30]
> rclone - Windows, AMD-64, v1.35 stable
> Rclone Browser - 1.1-9792a8b
> Using `Crypt` overlayed on `Amazon Cloud Drive`

When cycling the naming of a directory, contents aren't refreshed. Illustrative example:

> Initial Name: `/Videos/TV Shows/...`
> Cycled Name: `/Videos/TV Series/...`
> Re-named back to **original**: `/Videos/TV Shows/...`

After the folder name has been cycled, the directory **isn't** refreshed. Perhaps include a force-refresh switch when renaming directories?

**Comment by mmozeiko** [comment]
I can reproduce this. I'll look into it.

**Comment by mmozeiko** [comment]
This now should be fixed. I'll prepare 1.2 release probably tomorrow.
