### ISSUE TITLE
Bandwidth reporting: LOG report and what Rclone Browser display aren't the same

### ISSUE THREAD

**Issue by the-researcher** [mmozeiko/RcloneBrowser#31]
> rclone - Windows, AMD-64, v1.35 stable
> Rclone Browser - 1.1-9792a8b
> Using Crypt overlayed on Amazon Cloud Drive

1. Perform a single file transfer with a large file (>8GB).
2. Expand the `Running` Job by clicking the green triangle.
3. Expand `Show Output` by clicking the black triangle to view output.
4. In the scrolling output field, you will see the following line:
`filename.ext: 33% done, 1.902 MBytes/s, ETA: 43m52s`
5. In the `Running` pane, the `Bandwidth` value is not identical to that being reported in the log.

Furthermore, the `Bandwidth` value in the `Running` pane seems to be summing speeds incorrectly. When multiple transfers are at 100% with checkers running, and a single transfer is still active, the reported `Bandwitdth` value in the `Show Output` pane isn't the same.

Minor detail, but this GUI front-end is awesome. Thanks so much!

**Comment by mmozeiko** [comment]
Bandwidth field is just getting value from rclone. I'm not summing anything :)

Can you check if bandwidth in rclone output is same as in Bandwidth field in GUI?
In the output section it should have something like this:

    2017/01/29 22:40:05
    Transferred:   96.438 MBytes (5.800 MBytes/s)
    Errors:                 0
    Checks:                 2
    Transferred:            0
    Elapsed time:       16.6s
    Transferring:
    *                  filename:  6% done, 1.964 MBytes/s, ETA: 5m14s

Check if bandwidth in Transferred line matches the one in GUI field. If it does, but you thing the value is wrong, then this is bug in rclone.

**Comment by the-researcher** [comment]
Yup! Looks like you're right. I'll look through their bug tracker and let them know.

Feel free to close this issue. I'll update this comment when I find the relevant thread in the rclone repo.

Thanks!
