### ISSUE TITLE
--drive-chunk-size

### ISSUE THREAD

**Issue by dingho** [mmozeiko/RcloneBrowser#36]
Just discovered this awesome tool.  Thank you so much.

Any plans to implement control of the --drive-chunk-size parameter?

**Comment by mmozeiko** [comment]
I really not sure what do with all the extra arguments. Adding them all to dialog will make it a bit scary (it is a bit overwhelming already now).

But currently you can easily add it to `Extra arguments` field in Transfer dialog. And anything else you want there.

**Comment by dingho** [comment]
Thank you.
