### ISSUE TITLE
Feature request:  add to "move" option

### ISSUE THREAD

**Issue by vampywiz17** [mmozeiko/RcloneBrowser#40]
If possible, add to "move" option, like the mounted filesystem.

**Comment by mmozeiko** [comment]
It has already has move option. See second screenshot: https://raw.githubusercontent.com/wiki/mmozeiko/RcloneBrowser/screenshot2.png

**Comment by vampywiz17** [comment]
Sorry, i think, move to file one folder to another. the same mounted file system.

**Comment by mmozeiko** [comment]
Now I understand what you are asking. You can do this already now, but it's not very intuitive. See my comments in #13 which was asked exactly about same thing and I wrote how to do that. It also has comments about potential improvements for this operation.
