### ISSUE TITLE
Thank you and a help with building on Raspbian

### ISSUE THREAD

**Issue by jnh746** [mmozeiko/RcloneBrowser#47]
I would like to say thank you for sharing this with everyone we really do appreciate it when people share their hard work to help the rest of us who don't have the time or knowledge to do these things.

 I am currently trying to install this on a raspberry pi 3 running raspberrian and have not been able to figure out a way to compile the package on it with your instructions. I'm fairly new to Linux and even newer on the raspberry pi. I haven't found a way to install qt on the pi and it is my  only Linux machine. So I am requesting if there is any way that you would be willing to pre-compile a package that would be able to be installed on the rasberrian version of debian jessie or help with instructions to do so. thank you

**Comment by mmozeiko** [comment]
To install Qt packages you should run `apt-get install qtbase5-dev`  Does that work? If not, please post the output with error message.
Additionally you'll need `g++` and `cmake` packages for building from source.

After installing these three, you should be able to run the build:

    $ git clone https://github.com/mmozeiko/RcloneBrowser.git
    $ cd RcloneBrowser
    $ mkdir build && cd build
    $ cmake .. -DCMAKE_BUILD_TYPE=RELEASE -DCMAKE_INSTALL_PPREFIX=/usr/local
    $ make && make install

Now the binary should be in `/usr/local/bin/rclone-browser` location. I'm not very familiar with raspbian, but it probably will also create icon in start menu under Network (or something similar).

I'll check later if I can easily build binary packages for Raspbian.

**Comment by jnh746** [comment]
Thank you for the help i got it running. I had to rerun the install command with sudo permissions to get it to install then i had to move the files from the /local area to the the "/" directories for them to show up and run in the system. not sure if i did something wrong that caused the need for this of if it has something to do with the way raspbian is setup. Thanks again for the help!
