### ISSUE TITLE
Downloading Shared Files from one Gdrive to another Gdrive

### ISSUE THREAD

**Issue by disgrace2029** [mmozeiko/RcloneBrowser#54]
Not sure if this is a glitch or a problem. I am copying files from a shared Gdrive to my Gdrive. I do this using the Download button. There is times it works, there is times it only halfway works and then there is times it doesn't work at all. I have tried doing this with single files or folders. With Folders it only copies some. Any help would be greatly appreciated.

**Comment by mmozeiko** [comment]
What happens with command-line rclone when you execute it with exact command as GUI does?

**Comment by disgrace2029** [comment]
Yeah about the Command-line...I tried to look into how to do that and tried but just could not figure out the right command to execute. I managed to add the Google Remote in, but its the Copying from one Dir to another command I am having trouble with. 

In Rclone Browser this is the Dir I am trying to copy from and to:
**Source:** Google:The Handmaids Tale
**Destination:** Google:Temp4

In Rclone this is my command line:
rclone copyto Google:The Handmaids Tale Google:temp3

This results in Command copyto needs two arguments maximum

**Comment by mmozeiko** [comment]
Because source and destination arguments are separated by space, how do you think rclone can figure out what is source and what is destination?

Is source=`Google:The` and destination=`Handmaids Tale Google:temp3` ? Local folder can have : symbol in name.
Or is source=`Google:The Handmaids` and destination=`Tale Google:temp3` ?

I hope you see where is the problem. You need make sure it doesn't misunderstand where one argument ends and second starts. That you can do by putting each argument in quotes:

`rclone copyto Google:"The Handmaids Tale" Google:"temp3"`

It's not necessary for temp3, but it doesn't hurt.
If you don't put spaces, it will simply thing there are too many arguments for copyto command:
arg1=Google:The
arg2=Handmaids
arg3=Tale
arg4=Google:temp3

**Comment by disgrace2029** [comment]
The Source is The Handmaids Tale
For testing purposes I was putting the Destination as Temp3

I saw somewhere else about the Quotes but wasnt sure about it.

I will give it a try and see what happens.

Thanks!!!

**Comment by disgrace2029** [comment]
Ok it works but it only copies 14 files within that one folder. I tried it with another folder and it does the same thing for like Season 1, 2, 3... Only 14 files are copied under each Season.

I go and look at my CMD and its only showing a Blinking _ below the Rclone command. 

What could be going on?

**Comment by mmozeiko** [comment]
If you are using version 1.36 then add `-v` to see verbose output.

**Comment by disgrace2029** [comment]
rclone-v1.36-windows-386>rclone -v copyto Google:"TempFolder/Hawaii Five 0" Google:"temp3"
2017/04/29 14:37:37 INFO  : Google drive root 'temp3': Modify window is 1ms
2017/04/29 14:38:37 INFO  :
Transferred:      0 Bytes (0 Bytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:        1m2s
Transferring:
 * Season 6/Hawaii.Five-0.S06E01.720p.WEB-DL.x264.350MB-Pahe.in.mkv
 * Season 6/Hawaii.Five-0.S06E02.720p.WEB-DL.x264.350MB-Pahe.in.mkv
 * Season 6/Hawaii.Five-0.S06E03.720p.WEB-DL.x264.350MB-Pahe.in.mkv
 * Season 6/Hawaii.Five-0.S06E04.720p.WEB-DL.x264.350MB-Pahe.in.mkv

2017/04/29 14:39:37 INFO  :
Transferred:      0 Bytes (0 Bytes/s)
Errors:                 0
Checks:                 0
Transferred:            0
Elapsed time:        2m2s
Transferring:
 * Season 6/Hawaii.Five-0.S06E01.720p.WEB-DL.x264.350MB-Pahe.in.mkv
 * Season 6/Hawaii.Five-0.S06E02.720p.WEB-DL.x264.350MB-Pahe.in.mkv
 * Season 6/Hawaii.Five-0.S06E03.720p.WEB-DL.x264.350MB-Pahe.in.mkv
 * Season 6/Hawaii.Five-0.S06E04.720p.WEB-DL.x264.350MB-Pahe.in.mkv

**Comment by disgrace2029** [comment]
This time its doing the same 4 files. I had that same problem with Rclone Browser. It would be in a constant loop.

**Comment by mmozeiko** [comment]
So this is not a problem with GUI, but with rclone itself. I suggest you to ask this same question in rclone forums. You can try adding `-vv` flag for even more verbose output logging and posting logs there. Maybe somebody will know what is wrong here.

**Comment by disgrace2029** [comment]
Ok thanks!!!...You have been very helpful...now I know the problem I was
having
