### ISSUE TITLE
[Question] Amazon Drive upload error

### ISSUE THREAD

**Issue by Julz2k** [mmozeiko/RcloneBrowser#58]
Hello,

I've a problem with some files not beeing uploaded even after raising the time for this command to 15 minutes.
--acd-upload-wait-per-gb=TIME

I don't know what's the problem, the files are only 900Mb to 2,2Gb large.
I let my computer upload yesterday night and I've uploaded 800GB of data cause the retried up to 10 times, still the file did not show up von Amazon Drive.

```
2017/05/17 17:50:24 4698_alexa_sara.mp4: Upload error detected but didn't finish upload: HTTP code 400: "400 Bad Request": response body: "{\"message\":\"Cannot complete upload\"}" ("400 Bad Request")
2017/05/17 17:50:24 pacer: Rate limited, sleeping for 666.145821ms (1 consecutive low level retries)
2017/05/17 17:50:24 pacer: low level retry 1/1 (error HTTP code 400: "400 Bad Request": response body: "{\"message\":\"Cannot complete upload\"}")
2017/05/17 17:50:24 4698_alexa_sara.mp4: Failed to copy: HTTP code 400: "400 Bad Request": response body: "{\"message\":\"Cannot complete upload\"}"
```

**Comment by mmozeiko** [comment]
Please try same command with rclone cli to very that this is not a problem with rclone itself. Because this sounds like something rclone is doing wrong/incorrect, not the GUI.

**Comment by Julz2k** [comment]
yep you're right!
Jusgt tested it via CLI and got an Error after 19% for the first file. So what can I do now?

**Comment by mmozeiko** [comment]
You can try asking same question on rclone forum: https://forum.rclone.org/
