### ISSUE TITLE
Application failed to start because platform plugin “windows” is missing

### ISSUE THREAD

**Issue by ozgurulukir** [mmozeiko/RcloneBrowser#59]
It is not starting

Latest 32bit version
 
error message: Application failed to start because platform plugin “windows” is missing

**Comment by ozgurulukir** [comment]
Hi, can you suggest a solution?

**Comment by mmozeiko** [comment]
Did you unpack all files from zip archive? Including `qt.conf` and `platforms\qwindows.dll`? Maybe you copied exe file somewhere else and didn't copy other dll/conf files with it?

**Comment by ozgurulukir** [comment]
Yes, i just unpacked zip archive (whole files) and rclonebrowser was not started with that message, maybe packed dll files are wrong?

**Comment by mmozeiko** [comment]
Hmm, I am pretty sure all dll files are in the zip. I am able to run 32-bit exe just fine on 32-bit win7 (clean win installation in VM, no previous software).

Are you sure you unpacked all files when running exe, and you are not running from explorer "zip" folder (it opens zip files as folders)?

Can you try running `cmd.exe` then setting path to `platforms` folder to `QT_QPA_PLATFORM_PLUGIN_PATH` variable like this:

    set QT_QPA_PLATFORM_PLUGIN_PATH=c:\path\to\rclone-browser-1.2-a1156a0-win32\platforms

and then execute RcloneBrowser.exe like this (in same window):

    c:\path\to\rclone-browser-1.2-a1156a0-win32\RcloneBrowser.exe

Does it run like this?

Another thing to try is DebugView: https://technet.microsoft.com/en-us/sysinternals/debugview.aspx
1) download & run it
2) open cmd.exe and execute:

    set QT_DEBUG_PLUGINS=1
    C:\path\to\RcloneBrowser.exe

3) Go to debug View and save log, and paste it here.

Maybe you can show screenshot of folder structure you are running exe from?

**Comment by ozgurulukir** [comment]
hi, it same, i did as you described, could this problem related with my version of windows which is Vista?

here debug log
[7520] QFactoryLoader::QFactoryLoader() checking directory path "C:/rclone-browser/platforms" ...
[7520] QFactoryLoader::QFactoryLoader() checking directory path "C:/rclone-browser" ...
[7520] QFactoryLoader::QFactoryLoader() checking directory path "C:/rclone-browser/platforms/platforms" ...
[7520] QFactoryLoader::QFactoryLoader() checking directory path "C:/rclone-browser/platforms" ...
[7520] This application failed to start because it could not find or load the Qt platform plugin "windows"
[7520] in "c:\rclone-browser\platforms".
[7520] 
[7520] Reinstalling the application may fix this problem.
[7520] Error - 
[7520] RtlWerpReportException failed with status code :-1073741772. Will try to launch the process directly
[7520]

**Comment by mmozeiko** [comment]
Oh, Vista. I was no thinking about it at all... Now when I run it in Vista VM I get exactly same error. I'll need to check what I need to change to support it on Vista. It should be possible to run it under Vista.

**Comment by ozgurulukir** [comment]
Thanks, but if this related with old vista, dont spend your time for this because i think there is possibly no solution.

**Comment by mmozeiko** [comment]
It seems Qt supports Vista only up to 5.6 version: https://doc.qt.io/qt-5/supported-platforms-and-configurations.html

I've build binary with Qt 5.6, can you please try it out and let me know if it works:  https://drive.google.com/uc?export=download&id=0B6NdBDx_PciXV3FiSTNZRWxja3M

If it works, I can simply use Qt 5.6 for 32-bit builds.
There only one minor difference from newer Qt versions - it doesn't refresh remote list automatically after rclone console is closed (when "Config" button is pressed).

**Comment by ozgurulukir** [comment]
Thank you you are so kind, QT 5.6 build is working.
