### ISSUE TITLE
Transfert queue / Simultaneous transfer limit

### ISSUE THREAD

**Issue by Maxou44** [mmozeiko/RcloneBrowser#6]
Hello,

Thanks for your software, it's awesome !

Can you add the ability to have a queue and limit simultaneous transfers ?

**Comment by mmozeiko** [comment]
Yes, definitely! See #1
I have it added already in source code, and I'll prepare new binaries later today or maybe tomorrow.

**Comment by Maxou44** [comment]
Thanks <3
