### ISSUE TITLE
Usage instructions would be nice . .

### ISSUE THREAD

**Issue by CottonEaster** [mmozeiko/RcloneBrowser#69]
It seems that your program is intended for people already familiar with Rclone. Still, it would be nice to have some usage instructions. It would be good also to mention that one needs to have rclone installed for 'RcloneBrowser' to work. Further, you might want to forestall the misunderstanding that your program makes use of an Internet browser program. Finally, it would be good were the program to provide a little more explanation when it opens a terminal; when that happened, my first thought was that something had gone wrong.

Thanks for your work.

**Comment by mmozeiko** [comment]
Right, this tool is just an extra for rclone command line tool. It is not mean as complete replacement. I'll think about it how I can add extra instructions, but I don't want it to be complete replacement for rclone. You'll need to understand how rclone works to use this GUI, I have no intention to change that.

What do you mean by "misunderstanding that your program makes use of an Internet browser program"? What makes somebody to think that this GUI uses internet browser?

**Comment by CottonEaster** [comment]
Thanks for your reply.

> What do you mean by "misunderstanding that your program makes use of an Internet browser program"? What makes somebody to think that this GUI uses internet browser?

Answer: the use of the word 'browser', combined with the fact that various network utilities - such as Syncthing - have a GUI that works through an Internet browser (such as, for example, Firefox).
