### ISSUE TITLE
Encryption / Decryption

### ISSUE THREAD

**Issue by compumatter** [mmozeiko/RcloneBrowser#76]
Love the browser.  Downright user friendly, intuitive and all the rest.

My clients encrypt their data prior to it being sent to backblaze b2.

Using the Rclone Browser I notice I can see all files in their native unencrypted state which is wonderful.

I am not an expert at the encryption / decryption process and frankly I do not see any other way this could be done but I must ask the question to be certain.

- When viewing the data from the cloud service (backblaze b2 in my case) it appears in its 'decrypted' form.  Is this data being downloaded as 'encrypted data' and then decrypted within the Rclone browser as part of its wonderfulness or is this data in some way being downloaded in an unencrypted format ?

Could you please verify this process.

Thanks.

Jay

**Comment by mmozeiko** [comment]
RcloneBrowser does not encrypt or decrypt anything on its own. It uses rclone command-line tool to do all the work. So your questions are pretty much about how rclone works.

When you are requesting to get data from encrypted remote, the rclone first downloads encrypted data from remote to local machine, decrypts it and then saves in unencrypted format.

If you are asking about filenames - then this is the same - rclone first gets encrypted file names from remote, decrypts them locally, and shows then to you unencrypted.

If you want to know how rclone works in more details, please consult the rcloen documentation at https://rclone.org/docs/ and visit rclone forum: https://forum.rclone.org/
