### ISSUE TITLE
RcloneBrowser.exe opens infinite times when launching

### ISSUE THREAD

**Issue by nicko88** [mmozeiko/RcloneBrowser#8]
When I run the RcloneBrowser.exe on my desktop, the program immediately starts opening itself hundreds of times until my system crashes.

This is an extremely strange behavior to me.  I have never experienced this kind of issue on my PC before.

I don't know for sure if the program is to blame or somehow it's my PC, but I didn't know where else to ask about it.

Windows 10 build 1607.

Any ideas?

**Comment by mmozeiko** [comment]
I think this is an issue with encrypted .rclone.conf file. Do you use one? If so, then currently you need to remove password from conf file.

I have implemented support for password protected config file in #2, but it's not yet in the binary release. I'll prepare one a bit later.

**Comment by nicko88** [comment]
Hmm, I'm actually not using an encrypted config, just normal plaintext config.

The first time I did open the program it was OK, and then when it asked for the path to my rclone I put that in and then boom it exploded into 100s of copies.  Then after restarting my PC and trying again kept happening.  I deleted everything and re-downloaded and tried again but same thing.

**Comment by mmozeiko** [comment]
You can delete settings in registry - HKCU\Software\rclone-browser.

What version of rclone do you have? Can you execute `rclone.exe version` in commandline, and paste the exact output?

**Comment by nicko88** [comment]
I'm so embarrassed!

So after seeing in the registry, I see I accidentally set my rclone.exe path to RcloneBrowser.exe!!!

I'm terribly sorry for wasting your time on this haha.  I had both exe in the same folder and they were right next to each other and I didn't see that I miss-clicked when setting the rclone.exe path.

Thanks for your help!

**Comment by mmozeiko** [comment]
haha, no problem. This is funny. So application was opening itself infinitely :)

I can put simple check so this doesn't happen to somebody else.
