### ISSUE TITLE
Unknown CMake command "use_pch".

### ISSUE THREAD

**Issue by fizwit** [mmozeiko/RcloneBrowser#87]
building from source on Linux Ubuntu
CMake 3.7.2

CMake Error at CMakeLists.txt:78 (use_pch):
  Unknown CMake command "use_pch".

CMake Warning (dev) in CMakeLists.txt:
  No cmake_minimum_required command is present.  A line of code such as

    cmake_minimum_required(VERSION 3.7)

  should be added at the top of the file.  The version specified may be lower
  if you wish to support older CMake versions for this project.  For more
  information run "cmake --help-policy CMP0000".

**Comment by mmozeiko** [comment]
Have you modified source? `use_pch` is defined here: https://github.com/mmozeiko/RcloneBrowser/blob/master/CMakeLists.txt#L39

**Comment by fizwit** [comment]
I am using the download from tag 1.2.  the download for tag 1.2 and download for master are very different than your link.
https://github.com/mmozeiko/RcloneBrowser/archive/master.zip has a very old version of CMakeLists.txt

**Comment by mmozeiko** [comment]
Tag 1.2 has exactly same line in CMakeLists.txt: https://github.com/mmozeiko/RcloneBrowser/blob/1.2/CMakeLists.txt#L39

**Comment by mmozeiko** [comment]
Oh, are you building from `src` folder? You need to start build from root, it has main CMakeLists.txt file which sets up bunch of stuff.
