### ISSUE TITLE
Just installed on mac, not working

### ISSUE THREAD

**Issue by fredjohnston** [mmozeiko/RcloneBrowser#90]
I dragged "Rclone Browser.app" to my applications, ran it, the config popped up.  Then filled in the questions:
-Rclone location: /usr/local/bin
-.rclone.conf location: /Users/Fred/.config/rclone
-StreamCommand: blank
-Mount options: blank

then NOTHING appear in Remotes/Jobs

if i click "Config..." it shows...
Last login: Tue Feb  6 18:26:40 on ttys001
FJ-MacMini:~ Fred$ /tmp/rclone_config.command ; exit;
/tmp/rclone_config.command: line 2: /usr/local/bin: is a directory
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]

-Not sure what i did wrong, or how to fix it.

![screen shot 2018-02-06 at 6 37 10 pm](https://user-images.githubusercontent.com/28265553/35890224-ce9ac95c-0b6c-11e8-8292-4f70634c061d.png)

**Comment by mmozeiko** [comment]
rclone location should be full path to rclone executable, for example, `/usr/local/bin/rclone`

You can leave .rcone.conf location empty, it will use default place where rclone expects conf file (if you are not passing this location explicitly to rclone binary, then you don't need to specify it also here).

**Comment by fredjohnston** [comment]
YOU ROCK, IT WORKS!
THANKS... I put screenshot here for others (although not necessary)


![screen shot 2018-02-06 at 8 13 37 pm](https://user-images.githubusercontent.com/28265553/35893290-4ad5031c-0b7b-11e8-9fb7-c188ce2d1fd1.png)

**Comment by kolotelo** [comment]
What should I put on 'Stream command' and 'Mout options' any clue/help/indication? rgds.
